name: Update Hurricane Overlay GIF

on:
  schedule:
    # Run at minute 5 past every hour to avoid clashing with other cron jobs
    - cron: '5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # we will use the GITHUB_TOKEN explicitly when pushing
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pillow shapely pyshp

      - name: Run overlay generator
        run: |
          python mc/weather/make_hurricane_overlay_gif.py \
            --output mc/weather/overlay_glm_hurricanes.gif

      - name: Commit and push if GIF changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          if [[ $(git status --porcelain mc/weather/overlay_glm_hurricanes.gif) ]]; then
            git add mc/weather/overlay_glm_hurricanes.gif
            git commit -m "chore: auto-update overlay GIF [skip ci]"
            git push origin HEAD
          else
            echo "No changes to commit."
          fi 
