name: Update Hurricane Overlay GIF

on:
  schedule:
    # Run at minute 5 past every hour to avoid clashing with other cron jobs
    - cron: '5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Set permissions for the GITHUB_TOKEN to allow writing to the repository.
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          # We don't persist credentials because we will use the GITHUB_TOKEN
          # explicitly for the push operation.
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pillow shapely pyshp

      - name: Run overlay generator
        run: |
          python mc/weather/make_hurricane_overlay_gif.py \
            --output mc/weather/overlay_glm_hurricanes.gif

      - name: Commit and push if GIF changed
        env:
          # The GITHUB_TOKEN is provided by GitHub Actions.
          # We've set the 'contents: write' permission above for it.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          
          # Check if the target file has changed
          if [[ $(git status --porcelain mc/weather/overlay_glm_hurricanes.gif) ]]; then
            echo "Changes detected. Committing and pushing..."
            git add mc/weather/overlay_glm_hurricanes.gif
            git commit -m "chore: auto-update overlay GIF [skip ci]"
            
            # FIX: Authenticate the push using the GITHUB_TOKEN.
            # We construct a special URL that includes the token.
            # GITHUB_REPOSITORY and GITHUB_REF_NAME are default environment variables
            # available in the runner (e.g., 'your-name/your-repo' and 'main').
            git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}" HEAD:${GITHUB_REF_NAME}
          else
            echo "No changes to commit."
          fi
