# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Site Build

on:
  schedule:
  - cron: "*/10 * * * *"
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pathlib colour markdown pillow python-dateutil imap_tools
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: setup git config
      run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git pull

    - name: Update site
      run: |
        # stop the build if there are Python syntax errors or undefined names
        cd src/
        python check_email.py ${{ secrets.EMAIL }} ${{ secrets.PASSWORD }}
        cd ..
        cd src/blog/
        python gen_blog.py
        cd ../..
        cd src/study/
        python gen_study.py
        cd ../..
        cd src
        python gen_page.py
        cd ..

    - name: commit
      run: |
        # Stage the file, commit and push
        git add *
        git commit -m "updated site"
        git push origin master
          

